// Bundles the graph WebView entry (src/webview/graph-main.tsx) into a single IIFE string
// that GraphCanvas.tsx embeds in the native WebView HTML. Mirrors the editor's
// build-editor.mjs so the mobile graph is the same React Flow canvas as web/desktop, just
// hosted in a WebView (React Flow is DOM-only). Re-run after editing GraphView.web.tsx or
// anything under src/webview/:
//   npm run build:graph -w @companion/app
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const entry = resolve(root, "src/webview/graph-main.tsx");
const out = resolve(root, "src/graphBundle.generated.ts");

// React Flow ships its styles as a side-effect CSS import; strip it from the JS bundle
// (esbuild would otherwise emit a separate CSS file). The stylesheet is embedded below
// and injected into the WebView HTML by GraphCanvas.tsx.
const stripCss = {
  name: "strip-css",
  setup(b) {
    b.onResolve({ filter: /\.css$/ }, (a) => ({ path: a.path, namespace: "empty-css" }));
    b.onLoad({ filter: /.*/, namespace: "empty-css" }, () => ({ contents: "", loader: "js" }));
  },
};

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2019"],
  minify: true,
  write: false,
  jsx: "automatic",
  // Match the web app: react-native → react-native-web, and prefer .web variants so the
  // design-system Icon and GraphView resolve to their DOM implementations.
  alias: { "react-native": "react-native-web" },
  resolveExtensions: [".web.tsx", ".web.ts", ".web.jsx", ".web.js", ".tsx", ".ts", ".jsx", ".js", ".json"],
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [stripCss],
});

const js = result.outputFiles[0].text;
const css = readFileSync(require.resolve("@xyflow/react/dist/style.css"), "utf8");
const contents =
  `// AUTO-GENERATED by scripts/build-graph.mjs — do not edit.\n` +
  `// Bundled React Flow graph, embedded in the native WebView HTML by GraphCanvas.tsx.\n` +
  `/* eslint-disable */\n` +
  `export const GRAPH_JS = ${JSON.stringify(js)};\n` +
  `export const GRAPH_CSS = ${JSON.stringify(css)};\n`;
writeFileSync(out, contents);
console.log(`graph bundle written: ${(js.length / 1024).toFixed(1)} kB → ${out}`);
