// Bundles the WebView editor entry (src/webview/main.ts) into a single IIFE string
// that Editor.tsx embeds in the native WebView HTML. Inlining keeps the editor fully
// offline (no CDN). Re-run after editing createEditor.ts or anything under webview/:
//   npm run build:editor -w @companion/editor
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const entry = resolve(root, "src/webview/main.ts");
const out = resolve(root, "src/editorBundle.generated.ts");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2019"],
  minify: true,
  write: false,
});

const js = result.outputFiles[0].text;
const contents =
  `// AUTO-GENERATED by scripts/build-editor.mjs — do not edit.\n` +
  `// Bundled ProseMirror editor, embedded in the native WebView HTML by Editor.tsx.\n` +
  `/* eslint-disable */\n` +
  `export const EDITOR_JS = ${JSON.stringify(js)};\n`;
writeFileSync(out, contents);
console.log(`editor bundle written: ${(js.length / 1024).toFixed(1)} kB → ${out}`);
